Estoque/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Inovare.urls'))

]

Inovare/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.main, name='main'),
    path('inicioadmin/', views.inicio_admin, name='inicioadmin'),
    path('inicioforn/', views.inicio_forn, name='inicioforn'),
    path('cadastrarfunc/', views.cadastrar_func, name='cadastrarfunc'),
    path('cadastroproduto/', views.cadastro_produto, name='cadastroproduto'),
    path('cadastroforn/', views.cadastro_forn, name='cadastroforn'),
    path('editar/', views.editar, name='editar'),
    path('movimentacoes/', views.movimentacao, name='movimentacoes'),
    path('relatorios/', views.relatorio_movimentacoes, name='relatorio_movimentacoes'),
    path('entradaprod/', views.registrar_entrada, name='entradaprod'),
    path('saidaprod/', views.registrar_saida, name='saidaprod'),
    path('galeria/', views.galeria, name='galeria'),

    
    path('editar_fornecedor/<int:id_fornecedor>/', views.editar_fornecedor, name='editar_fornecedor'),
    path('listar_fornecedores/', views.listar_fornecedores, name='listar_fornecedores'),
    path('deletar_fornecedor/<int:id_fornecedor>/', views.deletar_fornecedor, name='deletar_fornecedor'),

    
    path('editar_funcionario/<int:id_funcionario>/', views.editar_funcionario, name='editar_funcionario'),
    path('listar_funcionarios/', views.listar_funcionarios, name='listar_funcionarios'),
    path('deletar_funcionario/<int:id_funcionario>/', views.deletar_funcionario, name='deletar_funcionario'),

    
    path('editar_produto/<int:id_produto>/', views.editar_produto, name='editar_produto'),
    path('listar_produto/', views.listar_produtos, name='listar_produto'),
    path('deletar_produto/<int:id_produto>/', views.deletar_produto, name='deletar_produto'),
]

#Define as URLs da sua aplicação Django

Inovare/models.py
from django.db import models
import uuid


class Funcionario_2(models.Model):
    id_funcionario = models.AutoField(primary_key=True)
    nome_funcionario = models.CharField(max_length=100)
    numero = models.CharField(max_length=15)
    email = models.EmailField(max_length=255, unique=True)
    data_nascimento = models.DateField()
    cpf = models.CharField(max_length=14, unique=True)
    rg = models.CharField(max_length=20, unique=True)

    def __str__(self):
        return self.nome_funcionario

    class Meta:
        verbose_name = "Funcionário_2"
        verbose_name_plural = "Funcionários_2"

class Fornecedor_2(models.Model):
    id_fornecedor = models.AutoField(primary_key=True)
    nome_fornecedor = models.CharField(max_length=100)
    cnpj = models.CharField(max_length=18, unique=True)
    telefone = models.CharField(max_length=20, unique=True)
    endereco = models.TextField()

    def __str__(self):
        return self.nome_fornecedor

    class Meta:
        verbose_name = "Fornecedor_2"
        verbose_name_plural = "Fornecedores_2"

class Produtos_2(models.Model):
    id_produto = models.AutoField(primary_key=True)
    nomeprod = models.CharField(max_length=100)
    desc = models.TextField()
    cod_barra = models.CharField(max_length=50, unique=True)
    quant = models.IntegerField()
    validade = models.DateTimeField(blank=True)
    fornecedor = models.ForeignKey(Fornecedor_2, on_delete=models.CASCADE)

    def __str__(self):
        return self.nomeprod

    class Meta:
        verbose_name = "Produto_2"
        verbose_name_plural = "Produtos_2"


class Relatorio_2(models.Model):
    id_relatorio = models.AutoField(primary_key=True)
    data_relat = models.DateTimeField(auto_now_add=True)
    responsavel = models.ForeignKey(Funcionario_2, on_delete=models.CASCADE)
    resumo = models.TextField()
    total_itens = models.IntegerField()
    valor_total = models.DecimalField(max_digits=10, decimal_places=2)
    entrada = models.IntegerField(null=True,blank=True)
    saida = models.IntegerField(null=True,blank=True)
    analise_rapida = models.BooleanField(default=False)
    recomendacoes = models.TextField(blank=True)
    produto = models.ForeignKey(Produtos_2, on_delete=models.CASCADE, default=False)

    def __str__(self):
        return f"Relatório {self.data_relat.strftime('%Y-%m-%d')}"

    class Meta:
        verbose_name = "Relatório_2"
        verbose_name_plural = "Relatórios_2"
        ordering = ['-data_relat']

#Define quatro modelos no Django, que representam entidades como Funcionários, Fornecedores, Produtos e Relatórios.
#O Django usa esses modelos para criar automaticamente as tabelas correspondentes no banco de dados.

Inovare/forms.py
from django import forms
from .models import Funcionario_2, Fornecedor_2, Produtos_2, Relatorio_2
import uuid

class FuncionarioForm(forms.ModelForm):
    class Meta:
        model = Funcionario_2
        fields = ['nome_funcionario', 'numero', 'email', 'data_nascimento', 'cpf', 'rg']

class FornecedorForm(forms.ModelForm):
    class Meta:
        model = Fornecedor_2
        fields = ['nome_fornecedor', 'cnpj', 'telefone', 'endereco']

class ProdutosForm(forms.ModelForm):
    fornecedor = forms.ModelChoiceField(
        queryset=Fornecedor_2.objects.all(),
        required=True,
        label="Fornecedor",
        empty_label="Selecione um fornecedor"
    )

    class Meta:
        model = Produtos_2
        fields = ['nomeprod', 'desc', 'cod_barra', 'quant', 'validade', 'fornecedor']


class RelatorioForm(forms.ModelForm):
    class Meta:
        model = Relatorio_2
        fields = ['responsavel', 'resumo', 'total_itens', 'valor_total', 'entrada', 'saida', 'analise_rapida', 'recomendacoes']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['responsavel'].queryset = Funcionario_2.objects.all()

#Cria formulários baseados nos modelos Funcionario_2, Fornecedor_2, Produtos_2, e Relatorio_2

Inovare/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from .models import Funcionario_2, Fornecedor_2, Produtos_2, Relatorio_2
from .forms import FuncionarioForm, FornecedorForm, ProdutosForm, RelatorioForm
from django.contrib.auth import authenticate, login
from django.contrib import messages
import uuid
import logging

logger = logging.getLogger(__name__)

# Login View
def login_view(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user and user.is_staff:
            login(request, user)
            return redirect('inicio_admin')
        else:
            messages.error(request, "Usuário ou senha inválidos.")
            logger.warning("Tentativa de login falhou para o usuário: %s", username)
    return render(request, 'login.html')

# Relatórios View
def relatorios(request):
    logger.info("Iniciando o relatório.")
    if request.method == 'POST':
        form = RelatorioForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                messages.success(request, "Relatório cadastrado com sucesso!")
                logger.info("Relatório salvo com sucesso.")
                return redirect('inicioadmin')
            except Exception as e:
                messages.error(request, "Erro ao cadastrar Relatório.")
                logger.error(f"Erro ao salvar relatório: {e}")
        else:
            messages.warning(request, "Formulário inválido. Verifique os campos.")
            logger.warning("Formulário inválido. Erros: %s", form.errors)
    else:
        form = RelatorioForm()
        logger.info("Requisição GET recebida, exibindo formulário vazio.")
    return render(request, 'relatorio.html', {'form': form})

# Main View
def main(request):
    return render(request, 'login.html')

# Admin Home View
def inicio_admin(request):
    return render(request, 'inicioadmin.html')

# Fornecedor Home View
def inicio_forn(request):
    return render(request, 'inicioforn.html')

# Editar View
def editar(request):
    return render(request, 'editar.html')

# Movimentações View
def movimentacao(request):
    return render(request, 'movimentacoes.html')

# Galeria View
def galeria(request):
    return render(request, 'galeria_imagem.html')

# Cadastrar Funcionário
def cadastrar_func(request):
    logger.info("Iniciando o cadastro de funcionário.")
    if request.method == 'POST':
        form = FuncionarioForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                messages.success(request, "Funcionário cadastrado com sucesso!")
                logger.info("Funcionário salvo com sucesso.")
                return redirect('inicioadmin')
            except Exception as e:
                messages.error(request, "Erro ao cadastrar funcionário.")
                logger.error(f"Erro ao salvar funcionário: {e}")
        else:
            messages.warning(request, "Formulário inválido. Verifique os campos.")
            logger.warning("Formulário inválido. Erros: %s", form.errors)
    else:
        form = FuncionarioForm()
        logger.info("Requisição GET recebida, exibindo formulário vazio.")
    return render(request, 'cadastrofunc.html', {'form': form})

# Cadastrar Fornecedor
def cadastro_forn(request):
    logger.info("Iniciando o cadastro de fornecedor.")
    if request.method == 'POST':
        form = FornecedorForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                messages.success(request, "Fornecedor cadastrado com sucesso!")
                logger.info("Fornecedor salvo com sucesso.")
                return redirect('inicioadmin')
            except Exception as e:
                messages.error(request, "Erro ao cadastrar fornecedor.")
                logger.error(f"Erro ao salvar fornecedor: {e}")
        else:
            messages.warning(request, "Formulário inválido. Verifique os campos.")
            logger.warning("Formulário inválido. Erros: %s", form.errors)
    else:
        form = FornecedorForm()
        logger.info("Requisição GET recebida, exibindo formulário vazio.")
    return render(request, 'cadastroforn.html', {'form': form})

# Cadastrar Produto
def cadastro_produto(request):
    logger.info("Iniciando o cadastro de produto .")
    if request.method == 'POST':
        form = ProdutosForm(request.POST)
        if form.is_valid():
            try:
                produto = form.save(commit=False)
                produto.cod_barra = uuid.uuid4()
                produto.save()
                messages.success(request, "Produto cadastrado com sucesso!")
                logger.info("Produto salvo com sucesso.")
                return redirect('inicioadmin')
            except Exception as e:
                messages.error(request, "Erro ao cadastrar produto.")
                logger.error(f"Erro ao salvar produto: {e}")
        else:
            messages.warning(request, "Formulário inválido. Verifique os campos.")
            logger.warning("Formulário inválido. Erros: %s", form.errors)
    else:
        form = ProdutosForm()
        logger.info("Requisição GET recebida, exibindo formulário vazio.")
    return render(request, 'cadastro_produto.html', {'form': form})

# Registrar Entrada de Produto
def registrar_entrada(request):
    logger.info("Iniciando a movimentação de produtos.")
    if request.method == 'POST':
        produto_id = request.POST.get('produto')
        entrada = int(request.POST.get('entrada', 0))
        responsavel_id = request.POST.get('responsavel')
        resumo = request.POST.get('resumo')
        total_itens = int(request.POST.get('total_itens', 0))
        valor_total = float(request.POST.get('valor_total', 0))
        analise_rapida = request.POST.get('analise_rapida')
        recomendacoes = request.POST.get('recomendacoes')

        try:
            produto = Produtos_2.objects.get(id_produto=produto_id)
            responsavel = Funcionario_2.objects.get(id_funcionario=responsavel_id)
        except (Produtos_2.DoesNotExist, Funcionario_2.DoesNotExist) as e:
            logger.error("Produto ou responsável não encontrados: %s", e)
            messages.error(request, "Produto ou responsável não encontrados.")
            return redirect('movimentacao_produto')


        produto.quant += entrada
        produto.save()

        Relatorio_2.objects.create(
            produto=produto,
            entrada=entrada,
            responsavel=responsavel,
            resumo=resumo,
            total_itens=total_itens,
            valor_total=valor_total,
            analise_rapida=analise_rapida,
            recomendacoes=recomendacoes,
        )

        messages.success(request, "Movimentação registrada com sucesso!")
        logger.info("Movimentação registrada com sucesso.")
        return redirect('relatorio_movimentacoes')

    else:
        produtos = Produtos_2.objects.all()
        funcionarios = Funcionario_2.objects.all()
        logger.info("Requisição GET recebida, exibindo formulário vazio.")
        return render(request, 'entradaprod.html', {
            'produtos': produtos,
            'funcionarios': funcionarios
        })


# Registrar Saída de Produto
def registrar_saida(request):
    logger.info("Iniciando a movimentação de produtos.")
    if request.method == 'POST':
        produto_id = request.POST.get('produto')
        saida = int(request.POST.get('saida', 0))
        responsavel_id = request.POST.get('responsavel')
        resumo = request.POST.get('resumo')
        total_itens = int(request.POST.get('total_itens', 0))
        valor_total = float(request.POST.get('valor_total', 0))
        analise_rapida = request.POST.get('analise_rapida')
        recomendacoes = request.POST.get('recomendacoes')

        try:
            produto = Produtos_2.objects.get(id_produto=produto_id)
            responsavel = Funcionario_2.objects.get(id_funcionario=responsavel_id)
        except (Produtos_2.DoesNotExist, Funcionario_2.DoesNotExist) as e:
            logger.error("Produto ou responsável não encontrados: %s", e)
            messages.error(request, "Produto ou responsável não encontrados.")
            return redirect('movimentacao_produto')

        produto.quant -= saida
        produto.save()

        Relatorio_2.objects.create(
            produto=produto,
            saida=saida,
            responsavel=responsavel,
            resumo=resumo,
            total_itens=total_itens,
            valor_total=valor_total,
            analise_rapida=analise_rapida,
            recomendacoes=recomendacoes,
        )

        messages.success(request, "Movimentação registrada com sucesso!")
        logger.info("Movimentação registrada com sucesso.")
        return redirect('relatorio_movimentacoes')

    else:
        produtos = Produtos_2.objects.all()
        funcionarios = Funcionario_2.objects.all()
        logger.info("Requisição GET recebida, exibindo formulário vazio.")
        return render(request, 'saidaprod.html', {
            'produtos': produtos,
            'funcionarios': funcionarios
        })

# Relatório de Movimentações
def relatorio_movimentacoes(request):
    movimentacoes = Relatorio_2.objects.select_related('responsavel', 'produto').all()
    filtro_entrada = Relatorio_2.objects.filter(entrada__gte=0)
    filtro_saida = Relatorio_2.objects.filter(saida__gte=0)
    print(filtro_entrada)
    print(filtro_saida)
    return render(request, 'relatorio.html', {
        'movimentacoes': movimentacoes,
        'filtro_entrada': filtro_entrada,
        'filtro_saida': filtro_saida
    })

def entrada_saida(request):
    filtro_entrada = Relatorio_2.objects.filter(entrada__gte=0)
    filtro_saida = Relatorio_2.objects.filter(saida__gte=0)
    return render(request, 'entrada_saida.html', {

Inovare/templates/editarforn.html
<!DOCTYPE html>
<html lang='pt-BR'>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Editar Fornecedor</title>
    {% load static %}
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='{% static "css/editarforn.css" %}'>
    <script src='{% static "js/editarforn.js" %}' defer></script>
</head>
<body>
    <header>
        <img class="img1" src="{% static 'images/logoBranca.png' %}" alt="Logo">
        <h3>Inovare Estoque Almoxarifado</h3>
        <a href="{% url 'inicioadmin' %}" class="botao-inicio">Voltar à Página Inicial</a>
    </header>

    <div class="main-container">
        <div class="cadastro-section">
            <h1 class="title">Editar Fornecedor</h1>
            <img src="{% static 'images/cadastro.png' %}" alt="Imagem de Cadastro" class="cadastro-image" id="imageSelector">
        </div>

         <div class="form-container">
            <form method="post" action="{% url 'editar_fornecedor' fornecedor.id_fornecedor %}">
                {% csrf_token %}
                <table>
                    <tbody>
                        <tr>
                            <td><label for="id_nome_fornecedor">Nome:</label></td>
                            <td>{{ form.nome_fornecedor }}</td>
                        </tr>
                        <tr>
                            <td><label for="id_cnpj">CNPJ:</label></td>
                            <td>{{ form.cnpj }}</td>
                        </tr>
                        <tr>
                            <td><label for="id_telefone">Telefone:</label></td>
                            <td>{{ form.telefone }}</td>
                        </tr>
                        <tr>
                            <td><label for="id_endereco">Endereço:</label></td>
                            <td>{{ form.endereco }}</td>
                        </tr>
                    </tbody>
                </table>

                <div class="button-container">
                    <input type="submit" value="Enviar" class="btn">
                    <input type="button" value="Voltar" onclick="window.location.href='{% url 'editar' %}';" class="btn">
                </div>
            </form>
        </div>
    </div>

    <footer>
        <div class="footer-container">
            <div class="footer-left">
                <ul class="contact-info">
                    <li>
                        <a href="https://www.instagram.com/"><img src="{% static 'images/instagram.png' %}" alt="Instagram"></a>
                        <a href="https://www.facebook.com/"><img src="{% static 'images/facebook.png' %}" alt="Facebook"></a>
                        <a href="https://bsky.app/"><img src="{% static 'images/bluesky.png' %}" alt="Bluesky"></a>
                    </li>
                    <li><a href="mailto:inovarealmoxarifado0102@gmail.com">inovarealmoxarifado0102@gmail.com</a></li>
                    <li><a href="tel:+5517994578543">(17) 9945-75843</a></li>
                </ul>
            </div>
            <img class="img2" src="{% static 'images/logoBranca.png' %}" alt="Logo">
            <div class="footer-right">
                <p>
                    Nosso papel é gerenciar e controlar materiais, incluindo armazenamento, controle de inventário, recebimento e conferência, distribuição e manutenção de registros, para garantir a disponibilidade eficiente e organizada dos suprimentos necessários para a operação da organização.
                </p>
            </div>
        </div>
    </footer>

<script>
    // Adiciona evento de clique na imagem
document.getElementById('imageSelector').addEventListener('click', function() {
    document.getElementById('fileInput').click(); // Simula o clique no input file invisível
});

// Adiciona evento para quando a imagem for selecionada ou capturada
document.getElementById('fileInput').addEventListener('change', function(event) {
    const file = event.target.files[0];
    if (file) {
        const reader = new FileReader();
        reader.onload = function(e) {
            document.getElementById('imageSelector').src = e.target.result; // Atualiza a imagem com a nova foto
        };
        reader.readAsDataURL(file);
    }
});

</script>
</body>
</html>

Inovare/templates/editarfunc.html
<!DOCTYPE html>
<html lang='pt-BR'>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Editar Funcionário</title>
    {% load static %}
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='{% static "css/editarfunc.css" %}'>
    <script src='{% static "js/editarfunc.js" %}'></script>
</head>
<body>
    <header>
        <img class="img1" src="{% static 'images/logoBranca.png' %}" alt="Logo">
        <h3>Inovare Estoque Almoxarifado</h3>
        <a href="{% url 'inicioadmin' %}" class="botao-inicio">Voltar à Página Inicial</a>
    </header>

    <div class="main-container">
        <div class="cadastro-section">
            <h1 class="title">Editar Funcionário</h1>
            <img src="{% static 'images/cadastroprod.png' %}" alt="Imagem de Cadastro" class="cadastro-image" id="imageSelector">
        </div>

        <div class="form-container">
            <form method="post" action="{% url 'editar_funcionario' funcionario.id_funcionario %}">
                {% csrf_token %}
                <table>
                    <tbody>
                        <tr>
                            <td><label for="id_nome_funcionario">Nome:</label></td>
                            <td>{{ form.nome_funcionario }}</td>
                        </tr>
                        <tr>
                            <td><label for="id_numero">Número:</label></td>
                            <td>{{ form.numero }}</td>
                        </tr>
                        <tr>
                            <td><label for="id_email">Email:</label></td>
                            <td>{{ form.email }}</td>
                        </tr>
                        <tr>
                            <td><label for="id_data_nascimento">Data de Nascimento:</label></td>
                            <td>{{ form.data_nascimento }}</td>
                        </tr>
                        <tr>
                            <td><label for="id_cpf">CPF:</label></td>
                            <td>{{ form.cpf }}</td>
                        </tr>
                        <tr>
                            <td><label for="id_rg">Número de Registro (RG):</label></td>
                            <td>{{ form.rg }}</td>
                        </tr>
                    </tbody>
                </table>

                <div class="button-container">
                    <input type="submit" value="Enviar" class="btn">
                    <input type="button" value="Voltar" onclick="window.location.href='{% url 'editar' %}';" class="btn">
                </div>
            </form>
        </div>
    </div>

    <footer>
        <div class="footer-container">
            <div class="footer-left">
                <ul class="contact-info">
                    <li>
                        <a href="https://www.instagram.com/"><img src="{% static 'images/instagram.png' %}" alt="Instagram"></a>
                        <a href="https://www.facebook.com/"><img src="{% static 'images/facebook.png' %}" alt="Facebook"></a>
                        <a href="https://bsky.app/"><img src="{% static 'images/bluesky.png' %}" alt="Bluesky"></a>
                    </li>
                    <li><a href="mailto:inovarealmoxarifado0102@gmail.com">inovarealmoxarifado0102@gmail.com</a></li>
                    <li><a href="tel:+5517994578543">(17) 9945-75843</a></li>
                </ul>
            </div>
            <img class="img2" src="{% static 'images/logoBranca.png' %}" alt="Logo">
            <div class="footer-right">
                <p>
                    Nosso papel é gerenciar e controlar materiais, incluindo armazenamento, controle de inventário, recebimento e conferência, distribuição e manutenção de registros, para garantir a disponibilidade eficiente e organizada dos suprimentos necessários para a operação da organização.
                </p>
            </div>
        </div>
    </footer>

    <script>
        // Adiciona evento de clique na imagem
        document.getElementById('imageSelector').addEventListener('click', function() {
            document.getElementById('fileInput').click(); // Simula o clique no input file invisível
        });

        // Adiciona evento para quando a imagem for selecionada ou capturada
        document.getElementById('fileInput').addEventListener('change', function(event) {
            const file = event.target.files[0];
            if (file) {
                const reader = new FileReader();
                reader.onload = function(e) {
                    document.getElementById('imageSelector').src = e.target.result; // Atualiza a imagem com a nova foto
                };
                reader.readAsDataURL(file);
            }
        });
    </script>
</body>
</html>

Inovare/templates/editarprod.html
<!DOCTYPE html>
<html lang='pt-BR'>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Editar Produtos</title>
    {% load static %}
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='{% static "css/editarprod.css" %}'>
    <script src='{% static "js/editarprod.js" %}'></script>
    <script src="https://cdn.jsdelivr.net/npm/jsbarcode@3.11.5/dist/JsBarcode.all.min.js"></script>
</head>
<body>
    <header>
        <img class="img1" src="{% static '/images/logoBranca.png' %}" alt="Logo">
        <h3>Inovare Estoque Almoxarifado</h3>
        <a href="{% url 'inicioadmin' %}" class="botao-inicio">Voltar à Página Inicial</a>
    </header>

    <div class="main-container">

        <div class="image-barcode-container">
            <h1>Editar Produto</h1>
            <img src="{% static '/images/cadastroprod.png' %}" alt="Imagem de Cadastro" class="cadastro-image" id="imageSelector">
            <svg id="barcode"></svg>
            <input type="file" id="fileInput" accept="image/*" capture="camera" style="display: none;">
        </div>

        <div class="form-container">
            <form method="post" action="{% url 'editar_produto' produto.id_produto %}">
                {% csrf_token %}
                <table>
                    <tbody>
                        <tr>
                            <td><label for="id_nomeprod">Nome:</label></td>
                            <td>{{ form.nomeprod }}</td>
                        </tr>
                        <tr>
                            <td><label for="id_desc">Descrição:</label></td>
                            <td>
                                {{ form.desc }}
                                {% if form.desc.errors %}
                                    <div class="error">{{ form.desc.errors }}</div>
                                {% endif %}
                            </td>
                        </tr>
                        <tr>
                            <td><label for="id_cod_barra">Código de Barras:</label></td>
                            <td>{{ form.cod_barra }}</td>
                        </tr>
                        <tr>
                            <td><label for="id_quant">Quantidade:</label></td>
                            <td>{{ form.quant }}</td>
                        </tr>
                        <tr>
                            <td><label for="id_validade">Validade:</label></td>
                            <td>{{ form.validade }}</td>
                        </tr>
                        <tr>
                            <td><label for="id_fornecedor">Fornecedor:</label></td>
                            <td>{{ form.fornecedor }}</td>
                        </tr>
                    </tbody>
                </table>

                <div class="button-container">
                    <input type="submit" value="Enviar" class="btn">
                    <input type="button" value="Voltar" onclick="window.location.href='{% url 'listar_produto' %}';" class="btn">
                </div>
            </form>
        </div>
    </div>


    <footer>
        <div class="footer-container">
            <div class="footer-left">
                <ul class="contact-info">
                    <li>
                        <a href="https://www.instagram.com/"><img src="{% static 'images/instagram.png' %}" alt="Instagram"></a>
                        <a href="https://www.facebook.com/"><img src="{% static 'images/facebook.png' %}" alt="Facebook"></a>
                        <a href="https://bsky.app/"><img src="{% static 'images/bluesky.png' %}" alt="Bluesky"></a>
                    </li>
                    <li><a href="mailto:inovarealmoxarifado0102@gmail.com">inovarealmoxarifado0102@gmail.com</a></li>
                    <li><a href="tel:+5517994578543">(17) 9945-75843</a></li>
                </ul>
            </div>
            <img class="img2" src="{% static 'images/logoBranca.png' %}" alt="Logo">
            <div class="footer-right">
                <p>
                    Nosso papel é gerenciar e controlar materiais, incluindo armazenamento, controle de inventário, recebimento e conferência, distribuição e manutenção de registros, para garantir a disponibilidade eficiente e organizada dos suprimentos necessários para a operação da organização.
                </p>
            </div>
        </div>
    </footer>

    <script>
        JsBarcode("#barcode", "123456789012", {
            format: "CODE128",
            width: 3,
            height: 50,
            displayValue: true
        });

        document.getElementById('imageSelector').addEventListener('click', function() {
            document.getElementById('fileInput').click();
        });

        document.getElementById('fileInput').addEventListener('change', function(event) {
            const file = event.target.files[0];
            if (file) {
                const reader = new FileReader();
                reader.onload = function(e) {
                    document.getElementById('imageSelector').src = e.target.result;
                };
                reader.readAsDataURL(file);
            }
        });
    </script>
</body>
</html>